name: Lint Code

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Lint with flake8
      run: |
        flake8 invoiceagent tests --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 invoiceagent tests --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics
    
    - name: Check imports with isort
      run: |
        isort --check --profile black invoiceagent tests
    
    - name: Check formatting with black
      run: |
        black --check --line-length 100 invoiceagent tests 